# # This is a basic workflow to help you get started with Actions
# #
# name : Connect to an AWS role from a GitHub repository

# # Controls when the action will run. Invokes the workflow on push events but only for the main branch
# on:
#   push:
#     branches: [ main ]
# #    paths:
# #      - .github/workflows/deployment.yaml
# #      - ./terraform/*
# env:
#   AWS_REGION : us-east-1 #Change to reflect your Region
#   BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
#   LATEST_COMMIT: ${{ github.event.push.head.sha }}

# # Permission can be added at job level or workflow level    
# permissions:
#       id-token: write   # This is required for requesting the JWT
#       contents: read    # This is required for actions/checkout

# jobs:
#   test:
#     name: auth check
#     runs-on: ubuntu-latest

#     steps:
#     - name: echo-git-attr
#       run: |
#         echo $BRANCH_NAME
#         echo $LATEST_COMMIT
#     - name: checkout
#       uses: actions/checkout@v3

#     - name: creds
#       uses: aws-actions/configure-aws-credentials@v3
#       with:
#           role-to-assume: arn:aws:iam::443370702075:role/GhaAssumeRoleWithAction #change to reflect your IAM role’s ARN
#           role-session-name: GitHub_to_AWS_via_FederatedOIDC
#           aws-region: ${{ env.AWS_REGION }}
#           audience: sts.amazonaws.com
#       # Test auth 
#     - name: S3 list
#       run: |
#         aws s3 ls tfstate-dev-us-east-1/


#   terraform-bootstrap:
#     name: bootstrap
#     needs: test
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: terraform/dev/bootstrap 
#     steps:
#     - name: Checkout the repository to the runner
#       uses: actions/checkout@v2

#     - name: Configure aws auth 
#       uses: aws-actions/configure-aws-credentials@v3
#       with:
#           role-to-assume: arn:aws:iam::443370702075:role/GhaAssumeRoleWithAction #change to reflect your IAM role’s ARN
#           role-session-name: GitHub_to_AWS_via_FederatedOIDC
#           aws-region: ${{ env.AWS_REGION }}
#           audience: sts.amazonaws.com

#     - name: setup terraform 
#       uses: hashicorp/setup-terraform@v3

#     - name: Terraform init
#       run: |
#         terraform init
        
#     - name: tf plan
#       run: |
#         terraform plan

#     - name: tf apply
#       run: |
#         terraform apply --auto-approve

